name: Daily Weather Pipeline

on:
  schedule:
    - cron: '0 7 * * *'        # Runs every day at 7 AM UTC
  workflow_dispatch:             # Lets you manually trigger from GitHub UI

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./   # All steps run here

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r weather_data/requirements.txt

      - name: Run pipeline
        run: python weather_data/main.py
      
      - name : Commit latest changes
        run: git config user.name = "github-actions"
             git config user.email = "actions@github.com"
             git add weather_data/data/ weather_data/models/ weather_data/models/test_models/
             git commit -m "Daily commit of new data" || echo "Nothing to commit"
             git push
